sysrev_project/sysrev_app/urls.py
from django.conf.urls import patterns, url
from sysrev_app import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
		url(r'^index', views.index, name='index'),
        url(r'^about', views.about, name='about'),
        url(r'^new_review', views.build_query, name='new_review'),
        url(r'^edit_review', views.edit_review, name='edit_review'),
        url(r'^delete_review', views.delete_review, name='delete_review'),
        url(r'^advanced/$', views.advanced, name='advanced'),
        url(r'^profile_page/$', views.profile_page, name='profile_page'),
        url(r'^results/$', views.results, name='results'),
        url(r'^docs/$', views.docs, name='docs'),
        url(r'^register/$', views.register, name='register'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^edit_profile/$', views.update_profile, name='edit_profile'),
        url(r'^create_review/$', views.new_review, name='create_review'),
        url(r'^final_results/$', views.final_results, name='final_results'),
        url(r'^actual_final_results/$', views.actual_final_results, name='actual_final_results'),
        url(r'^count_results/$', views.expected_results, name='count_results'),
        )

sysrev_project/sysrev_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from registration.backends.simple.views import RegistrationView


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sysrev_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sysrev_app/', include('sysrev_app.urls')),
                       # in-app urls.py  
)
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

sysrev_project/sysrev_app/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

class Researcher(models.Model):
    researcher = models.OneToOneField(User)
    affiliation = models.CharField(max_length=200)
    def __unicode__(self):
        return self.researcher.username

class Review(models.Model):
    reviewID = models.IntegerField(unique=True)
    reviewTitle = models.CharField(max_length = 500)
    researcher = models.ForeignKey(Researcher, on_delete=models.CASCADE)
    complete = models.BooleanField()
    def __unicode__(self):
        return str(self.reviewID)

class Query(models.Model):
    review =  models.ForeignKey(Review)
    Type = models.BooleanField() #novice/expert
    string = models.CharField(max_length=200)
    def __unicode__(self):
        return self.string

class Result(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    query = models.ForeignKey(Query, on_delete=models.CASCADE)
    ID = models.CharField(primary_key=True, max_length=10)
    authors = models.CharField(max_length=10000)
    title = models.CharField(max_length=1000)
    date = models.DateField()
    abstract = models.CharField(max_length=10000)
    link = models.CharField(max_length=1000)
    abstractApproved = models.BooleanField()
    documentApproved = models.BooleanField()
    reason = models.CharField(max_length = 10000)
    def __unicode__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    organization = models.CharField(max_length=200, blank=True)
    def __unicode__(self):
        return self.user.username

sysrev_project/sysrev_app/forms.py
from django import forms
from django.contrib.auth.models import User
from sysrev_app.models import UserProfile, Result, Review


class RevForm(forms.ModelForm):
    reviewTitle = forms.CharField(required=True)
    
    class Meta:
        model = Review
        fields = ('reviewTitle',)

class UserForm(forms.ModelForm):
    username = forms.CharField(help_text="Please enter a username.")
    email = forms.CharField(help_text="Please enter your email.")
    password = forms.CharField(widget=forms.PasswordInput(), help_text="Please enter a password.")

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):

    organization = forms.CharField(help_text="Please enter your organization.", required=False)
    website = forms.URLField(help_text="Please enter your website.", required=False)
    picture = forms.ImageField(help_text="Select a profile image to upload.", required=False)

    class Meta:
        model = UserProfile
        fields = ('organization', 'website', 'picture')

class UpdateProfile(forms.ModelForm):
    username = forms.CharField(required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_email(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')

        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise forms.ValidationError('This email address is already in use. Please supply a different email address.')
        return email

    def save(self, commit=True):
        user = super(UserProfileForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

sysrev_project/sysrev_app/views.py
from django.shortcuts import render, render_to_response
from sysrev_app.forms import UserForm, UserProfileForm, UpdateProfile, RevForm
from django.contrib.auth.models import User
from sysrev_app.models import UserProfile, Result, Query, Review, Researcher
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from sysrev_project.settings import MEDIA_URL
from sysrev_app.pubMed_search import search
from sysrev_app.search_count import rC
from django.template import RequestContext
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def index(request):
    try:

        userid = User.objects.get(username=request.user)
        researcher = Researcher.objects.get(researcher=userid)
        reviews_list = Review.objects.all().filter(researcher=researcher)        
    
    except:
        reviews_list = []

    return render(request, 'sysrev_app/index.html',{'reviews_list':reviews_list})

def about(request):
    context_dict = {'bold': "This is an about page"}
    return render(request, 'sysrev_app/about.html', context_dict)



def register(request):
    registered = False
    print request.method
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            
            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            name = user_form.cleaned_data.get('username')
            u = Researcher(researcher=User.objects.get(username=name))
            u.save()
            registered = True
        else:
            print user_form.errors, profile_form.errors
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request,
            'sysrev_app/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered} )


try:
    LATEST_REV_ID = getattr(Review.objects.latest('reviewID'),'reviewID') # fetches the id of the latest review
except:
    LATEST_REV_ID = 1 #if there are no reviews in the database


def new_review(request):
    print "NEW REVIEW"
    global LATEST_REV_ID
    USER = request.user
    if USER.is_authenticated() == False:
        return user_login(request)
    else:
        rev_form = RevForm(request.POST)
        if request.method == 'POST':# and rev_form.is_valid():
            reqPost = True
            print "IS POST"
            if rev_form.is_valid():                
                userid = User.objects.get(username=request.user).id
                researcherPerson = Researcher.objects.get(researcher = userid)
                title = rev_form.cleaned_data['reviewTitle']
                LATEST_REV_ID += 1 #increments current latest to ensure unique ids
                r = Review(reviewID=LATEST_REV_ID,reviewTitle= title , researcher = researcherPerson, complete = False)
                r.save()
            else:
                reqPost = False
                print rev_form.errors
                       
            
        # elif request.method == "GET" :
        #     reqPost = True
        #     revID = int(request.GET['revID'])
        #     rev = Review.objects.get(reviewID=revID)
        #     q = Query.objects.get(review=rev)
        #     results = Result.objects.filter(review=rev,query=q,abstractApproved=True,documentApproved=True)

        else:            
            reqPost = False
            rev_form = RevForm()
        return render(request,
                'sysrev_app/create_review.html',
                {'rev_form': rev_form, 'reqPost': reqPost})


def build_query(request):
    try:
        global LATEST_REV_ID
        userid = User.objects.get(username=request.user).id
        researcherPerson = Researcher.objects.get(researcher = userid)
        r = Review.objects.all().filter(reviewID=LATEST_REV_ID, researcher = researcherPerson)
        return render(request, 'sysrev_app/new_review.html',{'revList':r})
    except:
        return register(request)

def edit_review(request):
    print "at edit page"
    try:
        userid = User.objects.get(username=request.user)
        researcher = Researcher.objects.get(researcher=userid)
        reviews_list = Review.objects.all().filter(researcher=researcher)        
    
    except:
        reviews_list = []

    return render(request, 'sysrev_app/edit_review.html',{'reviews_list':reviews_list})

def delete_review(request):
	try:
		u = User.objects.get(username=request.user)
		Researcher.objects.get(researcher=u.id)
		return render(request, 'sysrev_app/delete_review.html')
	except:
		return user_login(request)

def advanced(request):
    return render(request, 'sysrev_app/advanced.html')

def results(request):
    if request.method == 'POST': 
        query = request.POST.get('txtOutput')
        typeOfQuery = 1
        rev = Review.objects.get(reviewID=LATEST_REV_ID)
        q = Query(review=rev,Type=typeOfQuery,string=query)
        q.save()
        results = search(query)
        if results is not None:
            errors = False
            alreadyExists = False
            resultsFound = True
            
            for result in results:
                
                q = Query.objects.get(review=rev)
                i = result['ID']
                l = result['Link']
                a = result['Authors']
                t = result['Title']
                d = result['Date']
                ab = result['Abstract']                
                r = Result(review = rev,link=l,query=q,ID=i,authors=a,title=t,date=d,abstract=ab,abstractApproved=0,documentApproved=0)
                try:
                    r.save()
                except:
                    pass
                
        else:
            results = "Nothing to see here, move along!"
            errors = True
            resultsFound = False
            alreadyExists = False
    else:
        try:
            revID= int(request.GET['revID'])
            rev = Review.objects.get(reviewID=revID)
            q = Query.objects.get(review=rev)
            result_objects = Result.objects.all().filter(review=rev)
            results = []
            for result_object in result_objects:
                r_dict = {}
                r_dict['ID'] = result_object.ID
                r_dict['Authors'] = result_object.authors
                r_dict['Title'] = result_object.title
                r_dict['Date'] = result_object.date
                r_dict['Abstract'] = result_object.abstract
                r_dict['Link'] = result_object.link
                r_dict['abstractApproved'] = result_object.abstractApproved
                r_dict['documentApproved'] = result_object.documentApproved
                results.append(r_dict)
            alreadyExists = True
            resultsFound = True
            errors = False
            print rev
            #return render(request, 'sysrev_app/results.html', {'results' : results,  'errors' : errors ,'query':q,'review': rev, 'alreadyExists':alreadyExists,'resultsFound':resultsFound,'revID':revID})
        except:
            revID= int(request.GET['revID'])
            rev = Review.objects.get(reviewID=revID)
            q = Query.objects.get(review=rev)
            resultsFound = False
            results = "Nothing to see here, move along!"
            errors = True
            alreadyExists = True
            #return render(request, 'sysrev_app/results.html', {'results' : results,  'errors' : errors,'query':q,'review': rev, 'alreadyExists':alreadyExists,'resultsFound':resultsFound})
        
    return render(request, 'sysrev_app/results.html', {'results' : results,  'errors' : errors, 'query':q,'review': rev,'alreadyExists':alreadyExists,'resultsFound':resultsFound})

def docs(request):
    if request.method == 'POST':
        checked = request.POST.getlist('checks[]')
        revID_List = request.POST.getlist('queryID')
        rev = Review.objects.get(reviewID= revID_List[0])
        q = Query.objects.get(review=rev)
        
        if len(revID_List) > 0:
            revID = revID_List[0]
        else:
            results = "Nothing to see here, move along!"
            return render(request, 'sysrev_app/final_results.html',{'results' : results}) 

        revObj = Review.objects.get(reviewID=revID)
        revObj.complete = False
        rev = Review.objects.all().filter(reviewID=revID)
        # print rev
        que = Query.objects.all().filter(review=revObj)
        # print que
        result_list = Result.objects.filter(review=revObj,query=que)
        #print result_list
        num = 1
        for result in result_list:
            if str(num) in checked:
                result.abstractApproved = True
                result.save()
            else:
                result.abstractApproved = False
                result.save()
            num += 1
        results = Result.objects.filter(abstractApproved=True,query=que)
        print results

    else:
        results = "Nothing to see here, move along!"
        q = []
        rev = ["no review"]
    return render(request, 'sysrev_app/docs.html',{'results' : results, 'query': q,'review':rev[0]})


def final_results(request):
    if request.method == 'POST':
        checked = request.POST.getlist('checks[]')
        revID_List = request.POST.getlist('queryID')
        reasons_List = request.POST.getlist('reasons')
        print checked
        print reasons_List

sysrev_project/templates/sysrev_app/about.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% load staticfiles %} <!-- New line -->


{% block title %}About page{% endblock %}

{% block body_block %}
<div id="AboutPage>
    <div id="Heading">
        <h1>About the Systematic Review Web Application</h1>
    </div>
    <div id="Text">
        <p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>
        <p>This is a web application which allows its users to perform systematic reviews using the PubMed API provided by the NCBI.</p>
	<p>It was developed in 2016 by group A from lab 3 as their WAD2 project.</p>
    </div>
	<p>The team consisted of:</p>
        <button class="abhide">Show</button>
	<li class="abname">Blagovest Tchasovnikarov</li>
	<li class="abname">Borislav Gachev</li>
	<li class="abname">Dafin Kozarev</li>
	<li class="abname">Kavisha Jayathunge</li>
</div>
{% endblock %}

sysrev_project/templates/sysrev_app/actual_final_results.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% load staticfiles %} <!-- New line -->


{% block title %}Review Results Saved{% endblock %}

{% block body_block %}
        <h1>Review Results Saved: {{review.reviewTitle}}</h1></br>        
        <div id="results" name="results">
			{% for key in results %}
			<div id="result_{{forloop.counter}}" class="displayAbstract">
				<div class="reason"><b>Reason selected: {{key.reason}}</b></div></br>
				<div class="id"><b>{{key.ID}}</b></div>
				<div class="title"><b>{{key.title}}</b></div>
				<div class="date">{{key.date}}</div>
				<div class="toggleAuthors"><i>[Author Information]</i></div>
				<div class="authors" style="display:none">{{key.authors}}</div></br>
				<div class="abstract" >{{key.abstract}}</div></br>
				<a href="{{key.link}}" class="btn btn-default" style="" target="_blank">Link to the full text</a><br>								
				<br><br>
			</div>	
			{% endfor %}
		</div>
		
{% endblock %}


{%block footer_block %}
	<footer class="footer">
		<div class="container">
         <nav>
		 <ul class="pager">
            <li><a href="#">Previous</a></li>
            <li><a href="#">Next</a></li>
          </ul>
        </nav>
	    </div>
    </footer>
{%endblock%}

sysrev_project/templates/sysrev_app/advanced.html
{% extends "base.html" %}

{% load staticfiles %}



{% block title %}Search{% endblock %}

{% block body_block %}

<form id="IndexSearch" class="form-horizontal" data-dbm="false" method="POST" action="{%url 'results' %}">
	{% csrf_token %}
	<div class="col-md-8">	
	<div class="">
		<h3 class="inline">Builder</h3>
	</div>
	<div class="form-group">
		<div class="input-group">
			<input type="text"  class="form-control" id = "txtOutput" name="txtOutput" placeholder="Use the fields below to build your query" aria-label="..." readonly />
			<span class="input-group-addon" id="resultCount"></span>
		</div>
	</div>
	<br>
	<div class="sb_line">
		<label for="fop_0" class="offscreen_noflow">Select Operation</label>

		<label for="ff_0" class="offscreen_noflow">Select Field</label>
		<div class="input_wrap">
			<label for="fv_1" class="offscreen_noflow">Field Value</label>
			<input id="fv_1" type="text" size="50" class="list_term_text jig-ncbiautocomplete" autocomplete="off" submit="false" />
			<input type="button" id="add_more_terms" class="add_line btn" href="#" title="Add new builder line" value="Add new line"/>
		</div>
	</div>
	<div class="whole_rhythm clear">
		<button class="btn btn-default" type="submit">Search</button>
	</div>
	</div>
</form>
    {% endblock %}

sysrev_project/templates/sysrev_app/delete_review.html
{% extends "base.html" %}

{% load static %}

{% block title %}Delete a review{% endblock %}
{% block body_block %}
	<h1>Please pick a review to delete.</h1>
{% endblock %}

sysrev_project/templates/sysrev_app/docs.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% load staticfiles %} <!-- New line -->





{% block title %}Document Pool{% endblock %}

{% block body_block %}

        <h1>Review: {{review.reviewTitle}}</h1>
        <h2>Links to full papers</h2></br>
        <form id="SelectDocument" class="advsec index_portlet" data-dbm="false" method="POST" action="{%url 'final_results' %}">
        {% csrf_token %}
        <input type="checkbox" name="queryID" class = "hidden" value="{{query.review}}" checked>
        <button class="btn btn-default" type="submit" name >Finish Review</button></br></br>

		<div id="doc_pool" name="results">
			{% for key in results %}
			<div id="result_{{forloop.counter}}" class="displayAbstract">
				<div class="id"><b>{{key.ID}}</b></div>
				<div class="title"><b>{{key.title}}</b></div>
				<div class="date">{{key.date}}</div>
				<div class="toggleAuthors"><i>[Author Information]</i></div>
				<div class="authors" style="display:none">{{key.authors}}</div></br>
				<div class="abstract" >{{key.abstract}}</div></br>
				<a href="{{key.link}}" class="btn btn-default" style="" target="_blank">Link to the full text</a></br></br>
				<input class = "checkbox" type="checkbox" name="checks[]" id="{{forloop.counter}}"> Select Document                
				<button class="reasonButton" name = "reasons" id ="{{forloop.counter}}" value="{{forloop.counter}}">Add Reason</button>​
				<div id="popup">
				<a class="b-close">x</a>
				<strong>Provide a reason for selecting this paper.</strong><br><br>
				<br><strong>Reason:</strong><br>
				<textarea value="{{forloop.counter}}" rows="4" cols="50">Please provide a reason for approving this paper. 
				</textarea>
				</div>
				
				<br><br>
			</div>	
			{% endfor %}
		</div>

	    </form >


{% endblock %}


{%block footer_block %}
	<footer class="footer">
		<div class="container">
         <nav>
		 <ul class="pager">
            <li><a href="#">Previous</a></li>
            <li><a href="#">Next</a></li>
          </ul>
        </nav>
	    </div>
    </footer>
{%endblock%}

sysrev_project/templates/sysrev_app/edit_profile.html
{% extends "base.html" %}

{% block title %}Edit Profile{% endblock %}

{% block body_block %}

{% load widget_tweaks %}
<div class="panel" style="padding-top: 60px;">
	<h1 class="panel-heading">Edit Profile</h1>
	<div class="panel-body">
		<!-- left column -->
		<div class="col-md-4 col-sm-6 col-xs-12">
				<div class="text-center">
				<img src="/media/{{profile_form.picture.value}}" class="img-circle avatar img-thumbnail" alt="avatar">
				<h6>Upload a different photo...</h6>
				<!--<input type="file" class="text-center center-block well well-sm">-->
				{{ profile_form.picture|add_class:"text-center center-block well well-sm" }}
				</div>
		</div>
		<!-- edit form column -->
		<div class="col-md-8 col-sm-6 col-xs-12 personal-info">
			<h3>Personal info</h3>
			<form class="form-horizontal" role="form" id="user_form" method="post" action="/sysrev_app/edit_profile/" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="form-group">
				<label class="col-lg-3 control-label">Username:</label>
				<div class="col-lg-8">
					{{user_form.username|add_class:"form-control"|attr:"readonly"}}
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-3 control-label">Email:</label>
				<div class="col-lg-8">
					{{user_form.email|add_class:"form-control"}}
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-3 control-label">Organisation:</label>
				<div class="col-lg-8">
					{{ profile_form.organization|add_class:"form-control"}}
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-3 control-label">Website:</label>
				<div class="col-lg-8">
					{{ profile_form.website|add_class:"form-control"}}
				</div>
			</div>
			<div class="form-group">
				<label class="col-md-3 control-label">Password:</label>
				<div class="col-md-8">
					{{user_form.password|add_class:"form-control"}}
				</div>
			</div>
			<div class="form-group">
				<label class="col-md-3 control-label"></label>
				<div class="col-md-8">
					<input class="btn btn-primary" value="Save Changes" type="submit">
					<span></span>
					<input class="btn btn-default" value="Cancel" type="reset">
				</div>
			</div>
			</form>
		</div>
	</div>
</div>



{% endblock %}

sysrev_project/templates/sysrev_app/edit_review.html
{% extends "base.html" %}
{% load smart_if %}
{% load staticfiles %}

{% block title %} Edit Review {% endblock %}
<link href="{% static "center-text.css" %}" rel="stylesheet">


     {% block body_block %}
     {% if user.is_authenticated %}


<style type="text/css">
#button {display:inline-block;margin-right:10px;} 
#status {display:inline-block;margin-right:10px;}
#link {display:inline-block;}
</style>

     <div class="page-header">
         <h1><b> Edit Reviews</b></h1> </br>
         {% if reviews_list|length > 0 %}
         <h3>Pick a review to edit:</h3> </br>
         {% for review in reviews_list %}
         {% if review.complete == False %}
         <div id="block_container">            
             <div id = "button"><h4> {{review.reviewTitle}} </h4></div>
             <div id = "link" ><a href="/sysrev_app/new_review/?revID={{review}}" class="btn btn-default" style="" target="_blank" >Edit</a></div>
         </div> 
         
         {% endif %}
                           
         {% endfor %}
         {% else %}
         <h3>No reviews present - please create one</h3> </br>
         {% endif %}

     {% else %}
         <h1><b>Welcome - Please sign in or register</b></h1> </br>
     {% endif %}
     </div>

{% endblock %}

sysrev_project/templates/sysrev_app/final_results.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% load staticfiles %} <!-- New line -->


{% block title %}Review Results{% endblock %}

{% block body_block %}
        <h1>Review Results: {{review.reviewTitle}}</h1></br>
        <form id="SelectDocument" class="advsec index_portlet" data-dbm="false" method="POST" action="{%url 'actual_final_results' %}">
        {% csrf_token %}
        <input type="checkbox" name="queryID" class = "hidden" value="{{query.review}}" checked>
        <button class="btn btn-default" type="submit" name = "saveRev" >Save Review Results</button></br></br>
        <div id="results" name="results">
			{% for key in results %}
			<div id="result_{{forloop.counter}}" class="displayAbstract">
				<div class="reason"><b>Reason selected: {{key.reason}}</b></div></br>
				<div class="id"><b>{{key.ID}}</b></div>
				<div class="title"><b>{{key.title}}</b></div>
				<div class="date">{{key.date}}</div>
				<div class="toggleAuthors"><i>[Author Information]</i></div>
				<div class="authors" style="display:none">{{key.authors}}</div></br>
				<div class="abstract" >{{key.abstract}}</div></br>
				<input type="checkbox" class= "hidden" name="checks[]" value="{{forloop.counter}}" checked>
				<a href="{{key.link}}" class="btn btn-default" style="" target="_blank">Link to the full text</a><br>								
				<br><br>
			</div>	
			{% endfor %}
		</div>
		</form >
{% endblock %}


{%block footer_block %}
	<footer class="footer">
		<div class="container">
         <nav>
		 <ul class="pager">
            <li><a href="#">Previous</a></li>
            <li><a href="#">Next</a></li>
          </ul>
        </nav>
	    </div>
    </footer>
{%endblock%}

sysrev_project/templates/sysrev_app/register.html
{% extends "base.html" %}


{% block body_block %}
<h1>Register</h1>

        {% if registered %}
        <br /><br /><strong>Thank you for registering!</strong><br /><br />
        <a href="/sysrev_app/login/">Please login.</a><br /><a href="/sysrev_app/">Or return to the homepage.</a><br />
        {% else %}
        	<strong>Register here!</strong><br />

        <form id="user_form" class="form-horizontal" method="post" action="/sysrev_app/register/" enctype="multipart/form-data">
			<fieldset>
            {% csrf_token %}
			{% load widget_tweaks %}

            <div class="col-lg-6">
                <div class="well well-sm"><strong><span class="glyphicon glyphicon-asterisk"></span>Required Field</strong></div>
                <div class="form-group">
                    <label for="id_username">Username:</label>
                    <div class="input-group">
						{% if user_form.username.errors%}
							{{user_form.username|add_class:"alert-danger form-control"}}
							<span class="alert alert-danger input-group-addon">
							<span class="glyphicon glyphicon-remove"></span>
						{% else %}
							{{user_form.username|add_class:"form-control"}}
							<span class="input-group-addon">
							<span class="glyphicon glyphicon-asterisk"></span>
						{%endif%}
						</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_email">Email:</label>
                    <div class="input-group">
                        {% if user_form.email.errors%}
							{{user_form.email|add_class:"alert-danger form-control"}}
							<span class="alert alert-danger input-group-addon">
							<span class="glyphicon glyphicon-remove"></span>
						{% else %}
							{{user_form.email|add_class:"form-control"}}
							<span class="input-group-addon">
							<span class="glyphicon glyphicon-asterisk"></span>
						{%endif%}
						</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password">Password:</label>
                    <div class="input-group">
                        {% if user_form.password.errors%}
							{{user_form.password|add_class:"alert-danger form-control"}}
							<span class="alert alert-danger input-group-addon">
							<span class="glyphicon glyphicon-remove"></span>
						{% else %}
							{{user_form.password|add_class:"form-control"}}
							<span class="input-group-addon">
							<span class="glyphicon glyphicon-asterisk"></span>
						{%endif%}
						</span>
					</div>
                </div>
                <div class="form-group">
                    <label for="id_website">Website:</label>
                    <div class="input-group">
                        {% if profile_form.website.errors%}
							{{profile_form.website|add_class:"alert-danger form-control"}}
							<span class="alert alert-danger input-group-addon">
							<span class="glyphicon glyphicon-remove"></span>
						{% else %}
							{{profile_form.website|add_class:"form-control"}}
							<span class="input-group-addon">
						{%endif%}
						</span>
                    </div>
                </div>
                <div class="form-group">
                	<label for="id_organization">Choose an organization:</label>
                	<div class="input-group">
                		{% if profile_form.organization.errors%}
                		{{profile_form.organization|add_class:"alert-danger form-control" }}
                		<span class="alert alert-danger input-group-addon">
                			<span class="glyphicon glyphicon-remove"></span>
                			{% else %}
                			{{profile_form.organization|add_class:"form-control" }}
                			<span class="input-group-addon">
                				{%endif%}
                			</span>
                		</div>
                	</div>
				<div class="form-group">
                    <label for="id_picture">Choose a profile picture:</label>
                    <div class="input-group">
                        {% if profile_form.picture.errors%}
							{{profile_form.picture|add_class:"alert-danger form-control" }}
							<span class="alert alert-danger input-group-addon">
							<span class="glyphicon glyphicon-remove"></span>
						{% else %}
							{{profile_form.picture|add_class:"form-control" }}
							<span class="input-group-addon">
						{%endif%}
						</span>
                    </div>
                </div>
                <input type="submit" name="submit" id="submit" value="Register" class="btn btn-info center-block">
            </div>			
            <!-- Provide a button to click to submit the form.
            <input type="submit" name="submit" value="Register" /> -->
			</fieldset>
		</form>
        {% endif %}
{% endblock %}